CREATE DATABASE `triple`;
CREATE TABLE `t_milege` (
  `F_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `F_REVIEW_ID` varchar(200) NOT NULL,
  `F_MILEGE` int(11) NOT NULL,
  `F_STATUS` varchar(2) NOT NULL,
  `F_TOTAL` int(11) NOT NULL,
  `F_REG_TIME` datetime NOT NULL,
  `F_ID` varchar(200) NOT NULL,
  PRIMARY KEY (`F_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8;
CREATE TABLE `t_review` (
  `F_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `F_ID` varchar(200) NOT NULL,
  `F_PLACE_ID` varchar(200) NOT NULL,
  `F_CONTENT` varchar(500) DEFAULT NULL,
  `F_PHOTO` varchar(1000) DEFAULT NULL,
  `F_REG_TIME` datetime NOT NULL,
  `F_STATUS` varchar(2) NOT NULL,
  `F_REVIEW_ID` varchar(200) NOT NULL,
  PRIMARY KEY (`F_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;
